### ISSUE TITLE
Packages yaml-dev and python-dev are not installed for setup of VM

### ISSUE THREAD

**Issue by tsariounov** [openblockchain/obc-dev-env#40]
In the vagrant VM setup script setup.sh, the line:

   "pip install -I flask==0.10.1 python-dateutil==2.2...."

needs packages yaml-dev and python-dev installed prior to executing since files yaml.h (used to build pyyaml) and Python.h (used to build MarkupSafe) are missing.

Probably need to apt-get install those before doing the pip install in setup.sh

**Comment by joequant** [comment]
Pull request #51 fixes this issue

**Comment by tsariounov** [comment]
Pull request #51 has been merged, closing issue.
