### ISSUE TITLE
when "vagrant up"

### ISSUE THREAD

**Issue by AllenField** [openblockchain/obc-dev-env#54]
![Image of Yaktocat](https://raw.githubusercontent.com/AllenField/obc-docs/master/issue/image/2016-03-17-1.jpg)

![Image of Yaktocat](https://raw.githubusercontent.com/AllenField/obc-docs/master/issue/image/2016-03-17-2.jpg)

![Image of Yaktocat](https://raw.githubusercontent.com/AllenField/obc-docs/master/issue/image/2016-03-17-3.jpg)

![Image of Yaktocat](https://raw.githubusercontent.com/AllenField/obc-docs/master/issue/image/2016-03-17-4.jpg)

![Image of Yaktocat](https://raw.githubusercontent.com/AllenField/obc-docs/master/issue/image/2016-03-17-5.jpg)

![Image of Yaktocat](https://raw.githubusercontent.com/AllenField/obc-docs/master/issue/image/2016-03-17-6.jpg)

![Image of Yaktocat](https://raw.githubusercontent.com/AllenField/obc-docs/master/issue/image/2016-03-17-7.jpg)

![Image of Yaktocat](https://raw.githubusercontent.com/AllenField/obc-docs/master/issue/image/2016-03-17-8.jpg)

![Image of Yaktocat](https://raw.githubusercontent.com/AllenField/obc-docs/master/issue/image/2016-03-17-9.jpg)

What can I do?

**Comment by srderson** [comment]
I've hit this before, It's like a connection failure during apt-get. Usually trying again will resolve the issue. Is this a persistent problem for you?

**Comment by AllenField** [comment]
Yes,you are right!
When I trying it again with VPN,everything is ok now!

**Comment by srderson** [comment]
Great, glad it is working for you now.
